<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\Core\ClipVault.Core\ClipVault.Core.csproj" />
    <ProjectReference Include="..\..\Infrastructure\ClipVault.Infrastructure\ClipVault.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="MahApps.Metro.IconPacks.Lucide" Version="6.2.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\Clipboard2.png" />
    <Content Include="Assets\Clipboard2.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Resource Include="Assets\Clipboard2.ico" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon>Assets\Clipboard2.ico</ApplicationIcon>
    <Version>1.0.2</Version>
    <FileVersion>1.0.2.0</FileVersion>
    <InformationalVersion>1.0.2</InformationalVersion>
  </PropertyGroup>

</Project>
